### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by HeJuKa** [ImpladeDeveloped/Battlegrounds#1]
Plug-in from SonsaYT,right?

**Comment by Zadezter** [comment]
You knew it.

**Comment by HeJuKa** [comment]
Ok thx flr creating ut then Working

**Comment by treehousemc1** [comment]
They bought from SonsaYT and public it

**Comment by Zadezter** [comment]
Yo yo yo. I got his download link with a virus codes that will make worlds and plugins get deleted.
I de-obfusecated the codes and fixed it.

**Comment by Zadezter** [comment]
Sonsa(FreakingDev) will get shocked rn.

**Comment by Zadezter** [comment]
I will close this issue.

**Comment by FreeGamingHere** [comment]
Credit me mate...

**Comment by Wolfkid200444** [comment]
Yee
