### ISSUE TITLE
Stupid - SonsaYT

### ISSUE THREAD

**Issue by treehousemc1** [ImpladeDeveloped/Battlegrounds#10]
he sooooooooooooooooooooooooooooooooooooooooooooooooooooooo angryyyyyyyyyyyyyyyyyy

**Comment by Zadezter** [comment]
LOL. If you hate him, expose him very bad.

**Comment by MrLukePotatoes** [comment]
he is really angry at me XD.

**Comment by treehousemc1** [comment]
we need to tell him its just    a-z  A-Z 1-9 and some symbols stuff only why so mad xD

**Comment by Zadezter** [comment]
I can still join his server.
IP: phcserver.cf
Port: 19132
---
I'lll join when he is offline.

**Comment by zBearchenPlayz** [comment]
I can Hacking the Server

**Comment by zBearchenPlayz** [comment]
Because They us a App auf Not a hosting website

**Comment by Zadezter** [comment]
Oh.

**Comment by zBearchenPlayz** [comment]
It is rlly easy

**Comment by treehousemc1** [comment]
If u can then u can fix it yourself https://github.com/ImpladeDeveloped/Battlegrounds/issues/9         also who edited my topic  title xD

**Comment by zBearchenPlayz** [comment]
XD

**Comment by MrLukePotatoes** [comment]
Zade probably

**Comment by FreeGamingHere** [comment]
Check my battlegrounds repo out now! It has some more new stuff

**Comment by Zadezter** [comment]
I already saw that, mate.
