### ISSUE TITLE
video

### ISSUE THREAD

**Issue by treehousemc1** [ImpladeDeveloped/Battlegrounds#2]
can i make a video about this plugin and credits u?

**Comment by Zadezter** [comment]
Idk. I think not now. Not this time.

**Comment by Zadezter** [comment]
I scared when Sonsa will watch your video.

**Comment by XFIREGANER** [comment]
yeah he is scammer dev

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by Zadezter** [comment]
Fuck you, sonsa.
