### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HeJuKa** [ImpladeDeveloped/Battlegrounds#3]
]: ErrorException: "include(phar:///home/gs/gs/data/servers/9867004/PocketMine-MP.phar/vendor/composer/../../src/pocketmine/block/StillWater.php): failed to open stream: phar error: Cannot open phar archive "/home/gs/gs/data/servers/9867004/PocketMine-MP.phar" for reading" (EXCEPTION) in "vendor/composer/ClassLoader" at line 444 2018-05-16 [10:22:12] [Asynchronous Worker #25 thread/DEBUG]: #0 vendor/composer/ClassLoader(444): pocketmine\error_handler(integer 2, string include(phar:///home/gs/gs/data/servers/9867004/PocketMine-MP.phar/vendor/composer/../../src/pocketmine/block/BlockFactory.php): failed to open stream: phar error: Cannot open phar archive "/home/gs/gs/data/servers/9867004/PocketMine-MP.phar" for reading, string phar:///home/gs/gs/data/servers/9867004/PocketMine-MP.phar/vendor/composer/ClassLoader.php, integer 444, array Array()) 2018-05-16 [10:22:12] [Asynchronous Worker #25 thread/DEBUG]: #1 vendor/composer/ClassLoader(444): include() 2018-05-16 [10:22:12] [Asynchronous Worker #6 thread/DEBUG]: #0 vendor/composer/ClassLoader(444): pocketmine\error_handler(integer 2, string include(phar:///home/gs/gs/data/servers/9867004/PocketMine-MP.phar/vendor/composer/../../src/pocketmine/block/StillWater.php): failed to open stream: phar error: Cannot open phar archive "/home/gs/gs/data/servers/9867004/PocketMine-MP.phar" for reading, string phar:///home/gs/gs/data/servers/9867004/PocketMine-MP.phar/vendor/composer/ClassLoader.php, integer 444, array Array()) 2018-05-16 [10:22:12] [Asynchronous Worker #25 thread/DEBUG]: #2 vendor/composer/ClassLoader(322): Composer\Autoload\includeFile(string phar:///home/gs/gs/data/servers/9867004/PocketMine-MP.phar/vendor/composer/../../src/pocketmine/block/BlockFactory.php) 2018-05-16 [10:22:12] [Asynchronous Worker #6 thread/DEBUG]: #1 vendor/composer/ClassLoader(444): include() 2018-05-16 [10:22:12] [Asynchronous Worker #25 thread/DEBUG]: #3 (): Composer\Autoload\ClassLoader->loadClass(string pocketmine\block\BlockFactory) 2018-05-16 [10:22:12] [Asynchronous Worker #6 thread/DEBUG]: #2 vendor/composer/ClassLoader(322): Composer\Autoload\includeFile(string phar:///home/gs/gs/data/servers/9867004/PocketMine-MP.phar/vendor/composer/../../src/pocketmine/block/StillWater.php) 2018-05-16 [10:22:12] [Asynchronous Worker #25 thread/DEBUG]: #4 src/pocketmine/level/generator/GeneratorRegisterTask(50): spl_autoload_call(string pocketmine\block\BlockFactory) 2018-05-16 [10:22:12] [Asynchronous Worker #6 thread/DEBUG]: #3 (): Composer\Autoload\ClassLoader->loadClass(string pocketmine\block\StillWater) 2018-05-16 [10:22:12] [Asynchronous Worker #25 thread/DEBUG]: #5 src/pocketmine/scheduler/AsyncTask(67): pocketmine\level\generator\GeneratorRegisterTask->onRun() 2018-05-16 [10:22:12] [Asynchronous Worker #6 thread/DEBUG]: #4 src/pocketmine/block/BlockFactory(88): spl_autoload_call(string pocketmine\block\StillWater) 2018-05-16 [10:22:12] [Asynchronous Worker #25 thread/DEBUG]: #6 (): pocketmine\scheduler\AsyncTask->run() 2018-05-16 [10:22:12] [Asynchronous Worker #6 thread/DEBUG]: #5 src/pocketmine/level/generator/GeneratorRegisterTask(50): pocketmine\block\BlockFactory::init()

**Comment by Zadezter** [comment]
🤔 Have you used PocketMine-MP.phar latest update?

**Comment by HeJuKa** [comment]
No

**Comment by HeJuKa** [comment]
Alpha12
