### ISSUE TITLE
This plugin Crashed PvP Like EggWars or no?

### ISSUE THREAD

**Issue by XFIREGANER** [ImpladeDeveloped/Battlegrounds#5]

**Comment by XFIREGANER** [comment]
What!

**Comment by HeJuKa** [comment]
DO IT ON EGGWARS AND NOT BATTLEGROUND AMK

**Comment by XFIREGANER** [comment]
And this plugin need resources pack😥😥

**Comment by XFIREGANER** [comment]
but Sonsa YT isn't Happy now🌚💔

**Comment by HeJuKa** [comment]
SonsaYT ist scammer Dev.

**Comment by HeJuKa** [comment]
I Hope Battleground Work,zadezter is good dev

**Comment by XFIREGANER** [comment]
Have you got his plugins??

**Comment by HeJuKa** [comment]
Yea i have

**Comment by HeJuKa** [comment]
With Virus!

**Comment by HeJuKa** [comment]
He is scammer...

**Comment by XFIREGANER** [comment]
Sonsa YT's Plugins is the best I Want it for 0$ Price💔😢

**Comment by HeJuKa** [comment]
SonsaYT?bis Plugins?He Download it from Other and Change codes

**Comment by XFIREGANER** [comment]
Tell me in Instgram Have you got?

**Comment by Zadezter** [comment]
Did I buy this plugin? No.
I got his download link with FULL OF VIRUS!
He leaked the plugin.

**Comment by HeJuKa** [comment]
I have got virus

**Comment by XFIREGANER** [comment]
What !!!!!

**Comment by Zadezter** [comment]
I de-obfusecated and fix the codes.

**Comment by XFIREGANER** [comment]
I Don't like sonsa yt

**Comment by MrLukePotatoes** [comment]
Hey Guys, This is Sonsa's Battleground plugin and We are removing the virus on it so You guys can go and play Battlegrounds on your server with friends for free. Not like other devs that their plugins are paid. 

Thanks, 
MrLukePotatoes
Zadezter's Best friend

**Comment by XFIREGANER** [comment]
The Best Dev🌚🌚🌚🌚

**Comment by Zadezter** [comment]
If I de-obfusecated it, that means I removed the virus from the codes.

**Comment by XFIREGANER** [comment]
Can You Tell me in instgram ZadeZter?

**Comment by Zadezter** [comment]
Okay. I'm gonna close this. I got 3 more issues opened!

**Comment by XFIREGANER** [comment]
Please I Want to tell you very important

**Comment by Zadezter** [comment]
I don't play Instagram anymore. @XFIREGANER

**Comment by XFIREGANER** [comment]
Please first give me your account name

**Comment by MrLukePotatoes** [comment]
We are gonna close this. In a minute...

**Comment by Zadezter** [comment]
But I have discord

**Comment by HeJuKa** [comment]
I dont Like tko

**Comment by XFIREGANER** [comment]
ok update worldGM Plugin

**Comment by MrLukePotatoes** [comment]
If you have discord. Contact us @MrLukePotatoes#1488 and Zadezter#0207

**Comment by XFIREGANER** [comment]
and LBAntiHack
I Hate Hacks

**Comment by HeJuKa** [comment]
Zadezter Discord Name?

**Comment by HeJuKa** [comment]
WorldGM is already Update
