### ISSUE TITLE
ARE YOU HAPPY NOW?

### ISSUE THREAD

**Issue by SonsaYT04** [ImpladeDeveloped/Battlegrounds#6]
...

**Comment by XFIREGANER** [comment]
Whattt !!!! SonaYT😱😱😱

**Comment by Zadezter** [comment]
Hahaha. You don't know I de-obfusecated your terrible codes?

**Comment by SonsaYT04** [comment]
You called it terrible? So why don't you create your own plugin?

**Comment by XFIREGANER** [comment]
What!!!! I Can't Understand What is happened???

**Comment by HeJuKa** [comment]
WHUT UP

**Comment by HeJuKa** [comment]
FACK YOU SONSAYT

**Comment by HeJuKa** [comment]
MY SERVER IS DELETE ALL FILES

**Comment by HeJuKa** [comment]
I HATE YOU YOU FACK SCAMMER

**Comment by SonsaYT04** [comment]
Karma is real

**Comment by XFIREGANER** [comment]
hey guys guys what is happened now???????

**Comment by HeJuKa** [comment]
Your mum ist real

**Comment by HeJuKa** [comment]
SonsaYT You fack nigga aka kanacke

**Comment by MrLukePotatoes** [comment]
HeJuKa, language.

**Comment by HeJuKa** [comment]
OK sorry Dude!

**Comment by XFIREGANER** [comment]
What is Happened??

**Comment by HeJuKa** [comment]
XFireGaner have You discord

**Comment by SonsaYT04** [comment]
@MrLukePotatoes  isa ka pa. Wala kang kwenta. Cancer ka sa pinas. Wala kang pakisama sa kapwa mo pinoy. Talagang nakikicooperate ka pa sa iba para lang mag leak ng plugin na hindi naman sa inyo.

**Comment by XFIREGANER** [comment]
HeJuKa are you buy BattleGround plugin from Sonsa YT?

**Comment by HeJuKa** [comment]
English ka....

**Comment by HeJuKa** [comment]
XFireGaner  You have Discord??

**Comment by Zadezter** [comment]
Omae wa mou shindeiru...

**Comment by XFIREGANER** [comment]
No I Don't have it but i have twitter

**Comment by HeJuKa** [comment]
Add me: @VaronPE_v2

**Comment by XFIREGANER** [comment]
ok

**Comment by HeJuKa** [comment]
Ok

**Comment by XFIREGANER** [comment]
tell me

**Comment by HeJuKa** [comment]
Name?

**Comment by XFIREGANER** [comment]
@AhmedAdam120

**Comment by SonsaYT04** [comment]
Changing message? Wow show me that you're a fucking wanna be developer. HAHAHAHA

**Comment by xXNiceAssasinl0** [comment]
Lmao Sonsa

**Comment by xXNiceAssasinl0** [comment]
He don’t wanna be Dev asshole @SonsaYT04

**Comment by XFIREGANER** [comment]
Sonsa YT What is happened?

**Comment by xXNiceAssasinl0** [comment]
@SonsaYT04 you make your own plugin like u didn’t copy colormatch

**Comment by Zadezter** [comment]
Shut up, Sonsa a.k.a FreakingDev.

**Comment by HeJuKa** [comment]
Yea,SonsaYT ist scammer dev

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by SonsaYT04** [comment]
So much wanna be developer HAHAHAHAHAHAHAHAAHAHAHAH
So much NOOOOOOOOB

**Comment by HeJuKa** [comment]
You can php?why then You Download PlayerHead or other?

**Comment by HeJuKa** [comment]
You Dev also?No You downloader

**Comment by XFIREGANER** [comment]
Sosna

**Comment by XFIREGANER** [comment]
@HeJuKa send me a message

**Comment by HeJuKa** [comment]
XFireGaner send Twitter name

**Comment by XFIREGANER** [comment]
my name is
@AhmedAdam120
XFireGamerYT

**Comment by HeJuKa** [comment]
Okay
