### ISSUE TITLE
** [ THIS IS IMPORTANT FOR ALL SERVER OWNERS ] **

### ISSUE THREAD

**Issue by Zadezter** [ImpladeDeveloped/Battlegrounds#7]
I recommend you to test a plugin on your own test servers.
Because I don't want it happens for your own server, when the virus codes from SonsaYT still in there.

**Comment by treehousemc1** [comment]
does sonsayt plugin rly have virus?

**Comment by HeJuKa** [comment]
Yes

**Comment by Zadezter** [comment]
Have you tested this plugin, and no errors found?

**Comment by MrLukePotatoes** [comment]
gg

**Comment by Zadezter** [comment]
Lol. It's fixed.
